### ISSUE TITLE
Proton transfer analyze

### ISSUE THREAD

**Issue by gcassone-cnr** [chenggroup/ai2-kit#4]
Dear developers, 

I've just installed the ai2-kit[all] with pip and I've noticed that some files are missing (e.g., the proton transfer test trajectory XYZ in /res directory). Additionally to this, I'm running a simple test on a XYZ file by using the simple command: 
ai2-kit algorithm proton-transfer analyze     --input_traj test.xyz \ --out_dir ./ \ --cell "[12.42,12.42,12.42,90,90,90]" \ --acceptor_elements '"[O]"' \ --initial_donors '[1]'
to make an initial test of the correct functioning of the algorithm. However, it returns to me the following error:
 File "/home/user/anaconda3/bin/ai2-kit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/anaconda3/lib/python3.12/site-packages/ai2_kit/main.py", line 130, in main
    Fire(ai2_kit)
  File "/home/user/anaconda3/lib/python3.12/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.12/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.12/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.12/site-packages/ai2_kit/algorithm/proton_transfer.py", line 177, in proton_transfer_detection
    u.dimensions = np.array(cell)
    ^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.12/site-packages/MDAnalysis/core/universe.py", line 748, in dimensions
    self.coord.dimensions = box
    ^^^^^^^^^^^^^^^^^^^^^
  File "MDAnalysis/coordinates/timestep.pyx", line 471, in MDAnalysis.coordinates.timestep.Timestep.dimensions.__set__
ValueError: could not convert string to float: './'

Could you please let me know why? 

Many thanks in advance and best wishes,
Giuseppe

**Comment by link89** [comment]
> I've just installed the ai2-kit[all] with pip and I've noticed that some files are missing (e.g., the proton transfer test trajectory XYZ in /res directory). Additionally to this, I'm running a simple test on a XYZ file by using the simple command:

The test trajectory is in `doc/res`: https://github.com/chenggroup/ai2-kit/blob/main/doc/res/proton-transfer-test-trajectory.xyz

You can try if testing trajectory works.

> File "MDAnalysis/coordinates/timestep.pyx", line 471, in MDAnalysis.coordinates.timestep.Timestep.dimensions.set
ValueError: could not convert string to float: './'

I guess MDA fail to process your trajectory. Can you share your trajectory?

**Comment by gcassone-cnr** [comment]
The problem is that the doc/res trajectory doesn't appear in my installation. These are the folders that appear under the /ai2-kit directory: algorithm  core  dflow  domain  feat  __init__.py  lib  main.py  __pycache__  res  tool  workflow

Here's my simple XYZ trajectory file


     193

  O         7.6732876250        6.3340029670        7.2816780822
  H         7.4782297543        7.3258702934        7.2062344290
  H         9.2698146375        3.9341200882        6.3884718425
  H         6.8689636812        5.8017359477        7.1730409459
  O         9.7472611689        0.2692034786        8.7638511720
  H         9.0062557277        0.6850164843        8.2286744260
  H        10.2815529409       -0.2601011913        8.1077718052
  O        10.2108928995        7.4355580827        5.3882649252
  H        10.9936213319        7.7409074895        5.9316548253
  H        10.4765180548        7.4636120138        4.4199416782
  O         5.5736410513       11.9510353074        7.9056523540
  H         5.0449770217       11.9724044482        7.0820048281
  H         5.9446203709       11.0121819296        7.9808872027
  O         4.5309826510       -0.4851235606        4.8871812567
  H         5.4768264498       -0.3557554174        4.6000414270
  H         4.2804392371       -1.4871780320        4.6879782702
  O         5.9319406058        8.8585486234        9.5250150677
  H         5.9418822358        9.7072996169       10.0817016350
  H         6.3545418839        8.8346040180        8.6140934040
  O         0.7915218338        1.9381356207        4.2991088679
  H         1.6206611921        2.0239724155        4.8975233215
  H         0.2426342832        2.7514610883        4.4139004305
  O        -0.5557979870        4.3366553003        8.7505753741
  H        10.8326104351        4.3728063694        8.6934811625
  H        -0.2049848933        4.9673586249        9.4598327083
  O         3.1958539260        2.1575296336       11.2206956083
  H         2.8112031612        1.2635041846       11.3384795873
  H         2.6112389975        2.8200704688       11.6380525150
  O         7.2856660460       -0.7419082911        4.3859328638
  H         7.6755352333        0.1394014416        4.6386157670
  H         7.5181974934       -0.7762336710        3.4012118223
  O         8.5943315356        1.5726520128        4.8035881625
  H         8.4993315564        2.5766584028        4.8286562863
  H         9.5913245025        1.3962544769        4.8136103099
  O         1.4054235141        0.0504839010        8.4645828367
  H         0.2228763198        1.1271510499        8.8054094749
  H         2.0461013428        0.4157054259        7.7937507516
  O         9.0318953198        5.3903901200        2.0528129404
  H         8.9130130592        4.6004679517        2.6709934464
  H         8.3993714423        5.9971823829        2.4626886497
  O         2.0906218039        3.3788668086        2.4183808506
  H         2.9745386895        3.0857773780        2.6970178747
  H         1.5080295181        2.6675915471        2.8500087442
  O        10.7456160531        7.9627566808        9.9684721101
  H        10.5496701918        8.7799501043       10.5511979658
  H        11.3462831201        8.3082874483        8.1087347221
  O         1.9344766029        5.0638241141        6.5184264025
  H         2.6265604961        4.8624583247        5.8587833905
  H         2.1920748734        4.3757150551        7.2292309294
  O         6.4982099029        9.2224678596        7.0750197169
  H         7.2379932884        9.1327316548        6.4031941308
  H         5.5291977190        9.0049283086        6.7257776460
  O         7.5958743635        3.0657941214       10.3368920945
  H         7.4548633648        3.7917180273       10.9397684028
  H         6.7896348499        2.5289261867       10.2795236994
  O        11.8436178949        8.4568978555        7.2847805042
  H        11.6075839559       10.3762843895        7.2321093210
  H         0.3627260047        8.1616127882        7.3884115143
  O        11.9055927956        1.7810198456        9.2286143083
  H        -0.4472821748        3.3337729721        8.9150191029
  H        11.0912187583        1.2560296466        8.9746247768
  O         8.4467398350       -0.7972213540       11.1609038414
  H         7.5342186592       -1.0834369906       11.4840031118
  H         8.5349905813       -0.5605648311       10.1629579886
  O        10.2987861924       10.0866089347       12.0037181780
  H         9.8021655096        9.7664745567       12.7426980048
  H         9.7067693726       10.9175803096       11.7445248668
  O         0.2004829679       -0.4016586179        1.1626111008
  H         1.1877104613       -0.4468335900        1.2908375585
  H         0.1319011718        0.2894183087       12.8127630890
  O        12.2324571117        8.6948063686        3.1284010729
  H        12.5056583087        8.6989994914        2.1741317910
  H        11.6332604757        9.4675399774        3.1370792772
  O         5.5299683809        1.2334494897       10.2384832559
  H         4.6165654437        1.7117440129       10.3637510566
  H         5.3778036369        0.7693973685        9.3809170194
  O        11.8330225701        1.8270567734       12.0928741263
  H        11.7829152979        1.6395785202       11.0584398484
  H        10.8985382049        1.6838410394       12.4407834863
  O         9.3114644589        4.3013112403        8.5579514382
  H         9.9123209463        7.4151723900        9.9776345805
  H         8.7721402563        3.8300985248        9.2634141033
  O        11.0316184921        0.3533425034        5.0136424536
  H        10.8253949414       -0.1949978246        4.2430210015
  H        11.9249893957        0.8079840952        4.8431181355
  O        -0.3381058364        4.4568832808        4.6584583948
  H        11.1979911709        4.6624390377        4.8672100784
  H         0.1910515241        4.5624513552        5.5140905235
  O         4.4431033708        4.4447783125        5.0727727757
  H         5.1262990048        4.3180021113        5.8189598358
  H         4.7829393004        3.9441776418        4.2818390171
  O         9.3809633317        4.1705324714        5.4433486814
  H         8.7804543920        5.0408687696        8.2070306806
  H         8.9897308929        5.0740186234        5.3608517241
  O         1.9476049006        7.5533582459        7.6297490561
  H         1.9339789852        6.6598431194        7.2569736094
  H         2.3741457109        7.6389676585        8.4943830896
  O         4.1138347777        8.6385882740        6.0050558029
  H         3.4332878665        8.1338697574        6.4555914848
  H         4.4747324286        8.1269043387        5.2468936068
  O         2.2271375646       11.7492654232       10.8787703574
  H         2.2400791074       10.8916005767       11.3842718762
  H         1.7954926941       11.6870935918        9.9861335874
  O        10.5002642433       -1.1327979564        2.7053760833
  H        11.2797479259       -0.7898458327        2.1837838931
  H         9.7450416962       -0.6692575374        2.1896610686
  O         4.7734887282        0.6293646967        1.4045257526
  H         4.5753872679        0.6580927037       12.8857225452
  H         4.1314187095       -0.0656866393        1.7657019963
  O         7.4058733253        7.1661502123        3.1370025420
  H         6.4310938711        7.0336102142        3.3363100543
  H         7.6511970279        7.7725641465        3.8230892972
  O         2.8574993355       11.2809766666        1.9283023676
  H         2.6852361074       10.7131240342        2.7641679505
  H         2.8791947452       10.5054697292        1.2669966609
  O         3.3419091547        3.7445258697        8.6792020432
  H         3.3204511299        2.7612964107        9.0507308974
  H         2.9193618288        4.3220867383        9.4254876284
  O         9.0179447950        1.8933623767       12.5608251070
  H         8.5020580679        2.2852178636       11.8024952290
  H         8.5695496906        1.0576398356       12.7263269429
  O         4.7453472392        5.3405885918       13.2645508995
  H         4.5368500530        4.4757489176        1.2736446122
  H         4.2384515081        5.2753750451       12.3275659847
  O         4.9596256784        3.0194821162        2.4715958771
  H         5.8558800866        3.1184154580        2.1046075454
  H         4.7143789188        2.0675894620        2.1210888113
  O         5.6010663997       -1.4685506472       11.0872866708
  H         5.4694594162       -0.5188717081       10.7420694167
  H         4.8057644726       -1.7704027255       11.6504825021
  O         0.1866454795        5.9630450352       10.5347393303
  H        12.1945045707        5.7115073228       11.4324320897
  H        12.2192757173        6.8543190693       10.4098867894
  O         7.3245784450        5.1760831462       12.1697390196
  H         7.9187243436        5.2653579142       12.9423938504
  H         6.4052359338        5.1063365853       12.5513458856
  O         3.2661598950        5.2351687748       11.0973815406
  H         3.2579576192        6.2326402708       10.7381714943
  H         2.3383973542        5.1786585423       11.3118649406
  O         1.4175171217        6.0125695104        2.4655269253
  H         1.0295798647        6.2904127809        3.3607712425
  H         1.5985007916        5.0295938656        2.5181148876
  O         3.7023062168        7.7749880630       10.1164105599
  H         3.3014607475        8.4154063862       10.8292219152
  H         4.5799155508        8.2570106600        9.8383805993
  O         8.1012679143        7.5867557436       11.1291728955
  H         7.4581191948        7.8873129685       10.4239106198
  H         7.7889384215        6.7599710566       11.4698552011
  O        12.4548274527        8.6670082711        0.5993590167
  H        11.8729979308        9.4080503926        0.2596026499
  H        11.9225174219        7.8691134137        0.5890966392
  O        11.4096968032        6.0724644798        0.8024040631
  H        10.5856965234        5.8495711514        1.2679694071
  H        12.1217000581        5.6816756426        1.4012369680
  O         7.4355177514       -0.6188254648        1.6449420166
  H         6.5575746778       -0.1597408724        1.6792194287
  H         7.1901860738       10.8685867644        1.3174857271
  O         3.6275086625        7.6192802229        1.5884154823
  H         2.7075890331        7.1754187562        1.8597752494
  H         4.1241200606        6.8274605392        1.3120417172
  O         7.4831877850        1.4162378622        7.4502259553
  H         7.7276203110        1.2588219460        6.4895138063
  H         6.8174621853        0.6909644234        7.6337990762
  O         2.5071380101        9.1193731574       12.1156689926
  H         1.5235192637        8.9660545715       -0.1359351329
  H         3.0054268538        8.4982416691        0.3004458507
  O         1.2846999506        3.8135131792       -0.0578185708
  H         0.4713508947        3.2273603974       -0.0954157554
  H         1.7485549379        3.6507770302        0.8184770879
  O         8.2533867584        9.0898889732        5.1838963277
  H         8.2085551319       10.0298378914        4.8418065155
  H         9.1474667958        8.5047923421        5.3838509417
  O         3.0984612456        1.7364999531        5.7647522586
  H         3.6133264339        2.5371403454        5.7444974038
  H         3.5815738905        0.9962220305        5.4152326988
  O         7.7887939788        2.8726836268        2.3829224047
  H         7.9471496399        2.0682521268        2.9340746783
  H         8.3389756487        2.5629508453        1.5739255685
  O         7.3099711786        9.2254152008        1.1321320622
  H         7.5368814164        8.6801576608        0.3404523704
  H         7.2574747059        8.5298292098        1.8464982134
  O         5.9212731222        3.9989722150        7.2665823359
  H         6.5548945044        3.3428874857        7.3993469216
  H         5.1874890166        3.7435014635        7.8306440073
  O        11.7863401207       11.3477056595        7.3339792351
  H        11.7456183758       -0.5677542933        6.4358924388
  H         0.7199890957       11.9010593339        7.9448980702
  O         2.1900461888        9.8217530620        4.1444628420
  H         2.7509151862        9.2680536284        4.8448707369
  H         1.3083270430        9.3370104999        4.1509788401
  O         4.8202684100        7.0841683693        3.9339215426
  H         4.2407554422        7.1959933174        3.1711408138
  H         4.6316092784        6.1086085623        4.2459481614
     193

  O         7.6793843865        6.3302266584        7.2802580395
  H         7.4859905842        7.3103300997        7.1994200736
  H         9.2639185611        3.9247083301        6.3725488298
  H         6.8989668093        5.7801447627        7.1855028050
  O         9.7543666281        0.2658754705        8.7644609856
  H         9.0182356582        0.6734893878        8.2525518761
  H        10.2798417676       -0.2709894951        8.1240349506
  O        10.2045361218        7.4305929954        5.3844960640
  H        10.9739723876        7.7564768337        5.9165924720
  H        10.4733750880        7.4966038548        4.4168378875
  O         5.5717157578       11.9571645595        7.9027989371
  H         5.0567211027       11.9657228979        7.1011877428
  H         5.9420351524       11.0236373602        7.9593194190
  O         4.5276609076       -0.4869853272        4.8904890051
  H         5.4725099507       -0.3303584898        4.6016610322
  H         4.3157950254       -1.4634634926        4.6958786088
  O         5.9313657264        8.8522882039        9.5295553967
  H         5.9377631045        9.7110607401       10.0824153722
  H         6.3620333904        8.8395979473        8.6131766596
  O         0.7887245965        1.9414904419        4.3010462748
  H         1.6239450123        2.0210971085        4.9274680769
  H         0.2254983950        2.7523560822        4.4082076705
  O        -0.5504999050        4.3361990221        8.7476125604
  H        10.7877691127        4.3713532172        8.6964834712
  H        -0.2216670828        4.9826460440        9.4546276731
  O         3.2016941627        2.1609574011       11.2255643784
  H         2.8180887061        1.2412019271       11.3460999787
  H         2.6136588609        2.8218870090       11.6390668003
  O         7.2786293503       -0.7429652070        4.3879144284
  H         7.6545283915        0.1371126713        4.6321046852
  H         7.5143832776       -0.7559200940        3.4190675812
  O         8.5913570994        1.5751790418        4.8074001464
  H         8.5343788457        2.5891908982        4.8484539785
  H         9.5924840700        1.3808037815        4.8031518731
  O         1.4127144968        0.0531293009        8.4611530039
  H         0.1992037311        1.1168588412        8.8139093378
  H         2.0150820545        0.4270477595        7.7894394504
  O         9.0296292558        5.3968223029        2.0549258432
  H         8.9144299266        4.5991377707        2.6636542533
  H         8.3736743134        6.0009919018        2.4662303007
  O         2.0908616681        3.3787076930        2.4117683263
  H         2.9674778484        3.0703499095        2.6871736605
  H         1.5003179066        2.6638807909        2.8423770042
  O        10.7461384800        7.9600747542        9.9678633634
  H        10.5226530385        8.7472440010       10.5471740251
  H        11.3426734166        8.2984323688        8.0956932816
  O         1.9366480371        5.0640627008        6.5100134113
  H         2.6346773537        4.8873155244        5.8577709405
  H         2.1652613660        4.3770642470        7.2195614278
  O         6.4999936763        9.2200119645        7.0761133674
  H         7.2450229615        9.1328222255        6.3990488867
  H         5.5565529645        8.9896128387        6.7448118989
  O         7.5979236586        3.0737373869       10.3404512186
  H         7.4530994569        3.7989692592       10.9479250908
  H         6.7638017781        2.5236880251       10.2516976033
  O        11.8398264086        8.4528707265        7.2833012011
  H        11.6295349580       10.3744658994        7.2214048916
  H         0.3903600742        8.1541048615        7.4123151563
  O        11.9064660076        1.7797215741        9.2335533444
  H        -0.4402239631        3.3250470527        8.9106940047
  H        11.0811494101        1.2696113944        8.9938182950
  O         8.4481078873       -0.8018155734       11.1607932809
  H         7.5366448915       -1.0787178569       11.4721288822
  H         8.5489023761       -0.5763811593       10.1851156718
  O        10.2945722297       10.0904312612       11.9975608053
  H         9.8013312946        9.7500049909       12.7674082939
  H         9.6984141300       10.9221437015       11.7645126970
  O         0.2054169618       -0.3986713765        1.1682107573
  H         1.1913366961       -0.4443846438        1.2955151371
  H         0.1462547206        0.2880011169       12.7831109619
  O        12.2350083490        8.6982948797        3.1373002723
  H        12.5037289969        8.6835152490        2.1667678475
  H        11.6420102592        9.4392106162        3.1482955670
  O         5.5262847961        1.2389521520       10.2345960973
  H         4.6099736780        1.6985445903       10.3586087714
  H         5.3666848680        0.7404732281        9.3758178969
  O        11.8284217035        1.8204305837       12.0993032408
  H        11.7732859569        1.6434508633       11.0458069165
  H        10.9078772716        1.6806134470       12.4184404067
  O         9.3117624093        4.3090944196        8.5553833912
  H         9.9068390121        7.4329183142       10.0109277177
  H         8.7407992079        3.8377343754        9.2437776059
  O        11.0309310703        0.3462204443        5.0134490626
  H        10.8152900108       -0.1800077969        4.2514886825
  H        11.9037765475        0.7997808187        4.8324203420
  O        -0.3391148180        4.4583533446        4.6621749932
  H        11.1850591625        4.6890603525        4.8680173616
  H         0.2001852204        4.5500544147        5.5174122723
  O         4.4497220444        4.4488358240        5.0680413336
  H         5.1192059149        4.3270784954        5.8109474175
  H         4.7707555055        3.9445150846        4.2671273163
  O         9.3822947349        4.1710030700        5.4431810338
  H         8.7736162472        5.0427948293        8.1762308164
  H         8.9852442002        5.0812249725        5.3472038883
  O         1.9427748430        7.5542576855        7.6344290015
  H         1.9409733610        6.6591547243        7.2549801723
  H         2.3890956150        7.6444120997        8.4735073407
  O         4.1151745615        8.6414550350        6.0009332382
   H         3.4289822050        8.1405954360        6.4583365803
  H         4.4731017093        8.1087455343        5.2490713385
  O         2.2222854613       11.7453573758       10.8767906985
  H         2.2560968007       10.8823654815       11.3728230635
  H         1.8017954217       11.6681643998        9.9838820043
  O        10.5011198733       -1.1341574533        2.7041667134
  H        11.3232784069       -0.7764633739        2.1850606261
  H         9.7239295460       -0.6673444160        2.2189960548
  O         4.7770417743        0.6204415984        1.4099576304
  H         4.5488349162        0.6753775709       12.8807096164
  H         4.1289410778       -0.0638853162        1.7771332344
  O         7.4099788577        7.1637785161        3.1409487891
  H         6.4498601917        7.0119451751        3.3275597160
  H         7.6766793157        7.7988904377        3.8403017949
  O         2.8459162559       11.2770944286        1.9277267690
  H         2.6912928156       10.7137849527        2.7769124054
  H         2.8425004730       10.5296537240        1.2353554911
  O         3.3444664577        3.7428556438        8.6734485181
  H         3.3184156622        2.7594095199        9.0419454398
  H         2.9375812140        4.3290404230        9.4245978010
  O         9.0173002113        1.8959126565       12.5536018073
  H         8.5259312507        2.2696726442       11.8071678416
  H         8.5751098518        1.0461729848       12.7351180209
  O         4.7443157853        5.3359914817       13.2653852240
  H         4.5390600321        4.4617004504        1.2707319749
  H         4.2476032636        5.3046850101       12.3236885247
  O         4.9555744805        3.0198358798        2.4685627173
  H         5.8764105094        3.1102453017        2.1254162827
  H         4.7013363947        2.0508694734        2.1050404576
  O         5.6022054359       -1.4700857155       11.0880063190
  H         5.4848110124       -0.5478498358       10.7286702221
  H         4.8052697739       -1.7839014023       11.6546252948
  O         0.1817386776        5.9683617904       10.5353977038
  H        12.1951940920        5.7069329203       11.4266669390
  H        12.2490082463        6.8717483045       10.3911046581
  O         7.3225941627        5.1798220310       12.1731904832
  H         7.9152303584        5.2670082981       12.9405041477
  H         6.3916625324        5.0993321798       12.5660555258
  O         3.2649668508        5.2382220794       11.0963174668
  H         3.2714036811        6.2497000397       10.7420419909
  H         2.3306035389        5.1795922745       11.3199958104
  O         1.4236033010        6.0151303159        2.4690328008
  H         1.0421486702        6.2898030677        3.3854310211
  H         1.5943230658        5.0394646338        2.5119773693
  O         3.7085113526        7.7771805124       10.1164393153
  H         3.3139840068        8.4069801327       10.8044678378
  H         4.5527289007        8.2443687448        9.8271859985
  O         8.0974081324        7.5872970048       11.1269124657
  H         7.4594826361        7.8879182808       10.4334558149
  H         7.7591294252        6.7411888605       11.4591101191
  O        12.4569293974        8.6655598501        0.6027228349
  H        11.8751323041        9.3960367450        0.2577006736
  H        11.9336407173        7.8873039694        0.5543972576
  O        11.4138797743        6.0747512292        0.8029745951
  H        10.5753317360        5.8334838171        1.2634913595
  H        12.0992791652        5.6627710888        1.3888503129
  O         7.4326548976       -0.6240723121        1.6514165758
  H         6.5510909497       -0.1930556849        1.6994586999
  H         7.1928831867       10.8929362350        1.3065959041
 O         3.6234561487        7.6133019943        1.5881641835
  H         2.7170069554        7.1383218251        1.8521753372
  H         4.1339047684        6.8082536628        1.3126222481
  O         7.4923398361        1.4159898418        7.4530653530
  H         7.7175568948        1.2747193114        6.5113220775
  H         6.8185427377        0.7047104775        7.6201594751
  O         2.5022388562        9.1230600083       12.1174897545
  H         1.5058783766        8.9616912268       -0.1527459512
  H         2.9838285851        8.4810000141        0.2789711424
  O         1.2889418599        3.8130639802       -0.0584739537
  H         0.4765091340        3.2261579914       -0.0913805523
  H         1.7365121723        3.6527179114        0.7976858636
  O         8.2483996827        9.0863848308        5.1835086312
  H         8.2182394646       10.0168430584        4.8258139239
  H         9.1183713185        8.5128228262        5.3997390904
  O         3.0953693315        1.7473786469        5.7641229846
  H         3.6137180977        2.5331753203        5.7593109938
  H         3.6069650948        1.0062741792        5.3951275055
  O         7.7844646915        2.8654151167        2.3817849932
  H         7.9775021262        2.0761980717        2.9556027376
  H         8.3367668188        2.5840022688        1.5771367805
  O         7.3064669722        9.2281318974        1.1274963534
  H         7.5283859711        8.6942731247        0.3439656703
  H         7.2456152205        8.5440082018        1.8342005568
  O         5.9250451274        3.9992671684        7.2647065313
  H         6.5698891969        3.3336572396        7.3953780238
  H         5.1580303489        3.7327076149        7.8258076577
  O        11.7875767125       11.3493357118        7.3312872868
  H        11.7279994443       -0.5548652592        6.4464695703
  H         0.7843042455       11.8860508025        7.9427953286
  O         2.1954275243        9.8179370312        4.1500402116
  H         2.7640512773        9.2855459111        4.8420171532
  H         1.3074487407        9.3440978725        4.1656667264
  O         4.8252260310        7.0886138727        3.9290113568
  H         4.2329353453        7.2165549135        3.1670561580
  H         4.6169530485        6.1208922380        4.2531727685

**Comment by link89** [comment]
> The problem is that the doc/res trajectory doesn't appear in my installation. These are the folders that appear under the /ai2-kit directory: algorithm core dflow domain feat init.py lib main.py pycache res tool workflow

I see. The doc is not part of package, you should download the source code or just download that file via the above link. Let's see if the sample trajectory works well so that we can narrow the problem.

**Comment by gcassone-cnr** [comment]
Hi, yes the sample trajectory works well. However, my trajectory gives always the same weird problem.

**Comment by gcassone-cnr** [comment]
Any clue? 

Best wishes,
Giuseppe

**Comment by link89** [comment]
I think you have to patch your xyz file by adding 
```
Atoms. Timestep: 0
```
in the empty line right after 163. I am not sure if there are tools to doing this, but it can be done by writing a simple python script.

**Comment by gcassone-cnr** [comment]
Nope, this doesn't solve the issue. I think it could be related to the Python environment with Anaconda3 and MDAnalysis/ai2-kit implementation. Don't you think?

**Comment by link89** [comment]
I think I figure out what's wrong, you don't need to use `\` if you put the command in a single line, I have used the following command against your trajectory and no errors is thrown.
```bash
ai2-kit algorithm proton-transfer analyze --input_traj test.xyz  --out_dir ./  --cell "[12.42,12.42,12.42,90,90,90]"  --acceptor_elements '"[O]"'  --initial_donors '[1]'
```

**Comment by gcassone-cnr** [comment]
Hi, yes, effectively now it works! Thanks a lot for your kind support!
Giuseppe
